version: '3.8'

services:
  web:
    build: .
    command: gunicorn base_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=base_app.settings
