# Generated by Django 5.0.6 on 2024-05-21 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0002_payments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=60, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("status", models.SmallIntegerField()),
                ("contract_version", models.CharField(max_length=30)),
                ("maximum_payment_date", models.DateTimeField(auto_now=True)),
                ("taken_at", models.DateTimeField(auto_now=True)),
                ("outstanding", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=60, unique=True)),
                ("total_amount", models.DecimalField(decimal_places=10, max_digits=20)),
                ("status", models.SmallIntegerField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.customer",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Payments",
        ),
    ]
