# Generated by Django 5.0.6 on 2024-05-21 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0003_loan_payment_delete_payments"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "loand_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finances.loan"
                    ),
                ),
                (
                    "payment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.payment",
                    ),
                ),
            ],
        ),
    ]
